// =========================================
// Supabase Configuration Template
// =========================================
// 
// IMPORTANT: This file will be auto-generated by setup.html
// Do not edit manually unless you know what you're doing
//
// After running the setup wizard, this file will contain:
// - SUPABASE_URL: Your project URL
// - SUPABASE_ANON_KEY: Your project's anon/public key
//
// You can find these values in:
// Supabase Dashboard > Settings > API
// =========================================

window.SUPABASE_CONFIG = {
  SUPABASE_URL: '',  // Will be set by setup wizard
  SUPABASE_ANON_KEY: ''  // Will be set by setup wizard
};

// Check if configuration is valid
window.isSupabaseConfigured = function() {
  return (
    window.SUPABASE_CONFIG.SUPABASE_URL && 
    window.SUPABASE_CONFIG.SUPABASE_ANON_KEY &&
    window.SUPABASE_CONFIG.SUPABASE_URL.startsWith('https://')
  );
};

// Fallback mode flag (when Supabase not configured)
window.FALLBACK_MODE = !window.isSupabaseConfigured();

if (window.FALLBACK_MODE) {
  console.warn('⚠️ Supabase not configured. Running in LocalStorage mode.');
  console.log('👉 Run setup.html to configure Supabase for full social features.');
}
